### ISSUE TITLE
Edit appointment not able to submit

### ISSUE THREAD

**Issue by SquilliamWallace** [SquilliamWallace/Radio-Tele-Frontend#116]
Gives an "invalid date" error, potentially an issue with the formatting

**Comment by cspath1** [comment]
The issues seems to be related to Google Chrome having less strict rules when instantiating Date objects than other browsers. This is why the issue does not appear in Chrome. I have fixed this when viewing log pages (which would also product an invalid date occasionally), and will fix it for the edit appointment section as well
