### ISSUE TITLE
Login Page: Background does not scale well as you shrink the browser

### ISSUE THREAD

**Issue by cspath1** [SquilliamWallace/Radio-Tele-Frontend#134]
As the browser size changes, the login page's background makes the input text hard to read due to the color contrast

**Comment by SquilliamWallace** [comment]
I believe Devin is working on styling for the login page right now so hopefully this should be resolved shortly

**Comment by cspath1** [comment]
> I believe Devin is working on styling for the login page right now so hopefully this should be resolved shortly

There is a chance we may want to go with a more neutral color background image for the login page. Just a thought

**Comment by SquilliamWallace** [comment]
May be a good idea, I'll see what I can find
