### ISSUE TITLE
Scheduling appointment does not work on development

### ISSUE THREAD

**Issue by jhopkins1** [SquilliamWallace/Radio-Tele-Frontend#143]
"JSON parse error: Cannot deserialize value of type `java.util.Date` from String "Invalid Date": not a valid...

**Comment by SquilliamWallace** [comment]
Is this on Firefox or Chrome? I had no issues yesterday

**Comment by jhopkins1** [comment]
chrome, but I think it just doesn't like how close I scheduled to current time

**Comment by SquilliamWallace** [comment]
yeah just tested it on chrome and it works fine

**Comment by jhopkins1** [comment]
wont allow for same day scheduling

**Comment by SquilliamWallace** [comment]
also works fine for me, we'll have to discuss and diagnose tomorrow
