### ISSUE TITLE
Celestial Bodies integration

### ISSUE THREAD

**Issue by jhopkins1** [SquilliamWallace/Radio-Tele-Frontend#181]

**Comment by SquilliamWallace** [comment]
I plan to get to this right after the scheduler rework, so i'm gonna self assign this one

**Comment by jhopkins1** [comment]
Might be done by then

**Comment by SquilliamWallace** [comment]
are you already working on it?

**Comment by jhopkins1** [comment]
yea have been for a few hours

**Comment by jhopkins1** [comment]
Actually it will be done by Monday
