### ISSUE TITLE
Account Activation Process Changes

### ISSUE THREAD

**Issue by cspath1** [SquilliamWallace/Radio-Tele-Frontend#198]
With the next version (which I am about to publish to the development server), the account activation process will be changed. This will not affect the front-end at all, except in one area.

We will need to modify the text displayed in the alert after a user registers for an account to reflect the new account activation process. 

The process is as follows:
* User Registers
* Admin approves user, and an AccountActivationToken will be sent to the user
* The user then uses a link to activate their account

**Comment by SquilliamWallace** [comment]
Heard, I can change that tonight
